### ISSUE TITLE
Website1

### ISSUE THREAD

**Issue by nikulsolanki** [tonyflo/tonyflo.github.io#1]
Gondal was once one of the eight princely states of Kathiawar before Indian Independence. The rulers here had a fascination for cars for which Gondal had the best-planned road system in Gujarat at that time. In 1643 AD, Gondal was founded by Thakore Shri Kumbhoji I Meramanji and then came into prominence during the time of Sir Bhagvat Singhji, who ruled Gondal till Independence. The Riverside Palace, which was built by him for his son Yuvraj

**Comment by tonyflo** [comment]
Spam
